services:
  postgres:
    image: postgres:15
    container_name: postgresDETECTIONFRAUDE
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - fraud-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminDETECTIONFRAUDE
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - fraud-network

  jupyter:
    build: ./notebooks
    container_name: notebookdETECTIONFRAUDE
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./models:/home/jovyan/work/models
      - ./ML:/home/jovyan/work/ML 
      - ./ML:/mlflow
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    depends_on:
      - postgres
      - mlflow
    networks:
      - fraud-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.18.0
    container_name: mlflow
    user: root
    ports:
      - "5001:5000"
    volumes:
      -  ./ML:/mlflow  
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
    command: bash -c "pip install mlflow && chmod -R 777 /mlflow && mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000 --gunicorn-opts '--forwarded-allow-ips=* --proxy-allow-from=*'"

      
    networks:
      - fraud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  
volumes:
  pgadmindata:
  postgresdata:

networks:
  fraud-network:
    driver: bridge