apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      enableServiceLinks: false  # ← CRITIQUE : Désactive les variables auto
      containers:
        - name: spark-worker
          image: apache/spark:3.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          command: ["/bin/bash", "-c"]
          args:
            - >
              /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
              spark://spark-master:7077
              --webui-port 8081;
              tail -f /dev/null
          env:
            - name: SPARK_WORKER_MEMORY
              value: "1g"
            - name: SPARK_WORKER_CORES
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark
    role: worker
  ports:
    - name: web
      port: 8081
      targetPort: 8081
  type: NodePort